import Foundation

public struct SwiftGenerator: Sendable {
    public var access: String

    public init(access: String = "public") {
        self.access = access
    }

    public func generate(_ schema: GraphQLSchemaDocument) -> String {
        var lines: [String] = [
            "// Generated by CoreGraphQL. Do not edit.",
            "",
            "import CoreGraphQL",
            "import Foundation",
            ""
        ]

        let builtin = Set(["String", "Int", "Float", "Boolean", "ID", "Upload"])
        for scalar in schema.scalars where !builtin.contains(scalar) {
            lines.append("\(access) typealias \(escape(scalar)) = String")
        }
        if schema.scalars.contains(where: { !builtin.contains($0) }) {
            lines.append("")
        }

        for item in schema.enums.sorted(by: { $0.name < $1.name }) {
            lines.append(contentsOf: generateEnum(item))
            lines.append("")
        }

        for item in schema.inputs.sorted(by: { $0.name < $1.name }) {
            lines.append(contentsOf: generateStruct(item, conformances: "Codable, Sendable"))
            lines.append("")
        }

        for item in (schema.objects + schema.interfaces).sorted(by: { $0.name < $1.name }) {
            lines.append(contentsOf: generateStruct(item, conformances: "Decodable, Sendable"))
            lines.append("")
        }

        for item in schema.unions.sorted(by: { $0.name < $1.name }) {
            lines.append(contentsOf: generateUnion(item))
            lines.append("")
        }

        while lines.last == "" {
            lines.removeLast()
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private func generateEnum(_ item: EnumDef) -> [String] {
        var lines = ["\(access) enum \(escape(item.name)): String, Codable, Sendable {"]
        var used: Set<String> = []
        for value in item.values {
            var caseName = camelCase(value)
            if used.contains(caseName) {
                caseName = escape(value)
            }
            used.insert(caseName)
            lines.append("    case \(escape(caseName)) = \"\(value)\"")
        }
        lines.append("}")
        return lines
    }

    private func generateStruct(_ item: ObjectDef, conformances: String) -> [String] {
        var lines = ["\(access) struct \(escape(item.name)): \(conformances) {"]
        for field in item.fields {
            lines.append("    \(access) var \(escape(field.name)): \(swiftType(field.type))")
        }
        if item.fields.isEmpty {
            lines.append("}")
            return lines
        }
        let params = item.fields.map { field in
            "\(escape(field.name)): \(swiftType(field.type))"
        }.joined(separator: ", ")
        lines.append("")
        lines.append("    \(access) init(\(params)) {")
        for field in item.fields {
            let name = escape(field.name)
            lines.append("        self.\(name) = \(name)")
        }
        lines.append("    }")
        lines.append("}")
        return lines
    }

    private func generateUnion(_ item: UnionDef) -> [String] {
        var lines = ["\(access) enum \(escape(item.name)): Decodable, Sendable {"]
        for member in item.members {
            lines.append("    case \(camelCase(member))(\(escape(member)))")
        }
        lines.append("    case unknown(String)")
        lines.append("")
        lines.append("    \(access) init(from decoder: any Decoder) throws {")
        lines.append("        enum TypenameKey: String, CodingKey { case __typename }")
        lines.append("        let type = try decoder.container(keyedBy: TypenameKey.self).decode(String.self, forKey: .__typename)")
        lines.append("        switch type {")
        for member in item.members {
            lines.append("        case \"\(member)\": self = .\(camelCase(member))(try \(escape(member))(from: decoder))")
        }
        lines.append("        default: self = .unknown(type)")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        return lines
    }

    private func swiftType(_ type: TypeRef) -> String {
        switch type {
        case .named(let name, let nullable):
            let mapped = mapNamed(name)
            return nullable ? "\(mapped)?" : mapped
        case .list(let inner, let nullable):
            let mapped = "[\(swiftType(inner))]"
            return nullable ? "\(mapped)?" : mapped
        }
    }

    private func mapNamed(_ name: String) -> String {
        switch name {
        case "Int": "Int"
        case "Float": "Double"
        case "Boolean": "Bool"
        case "String", "ID": "String"
        case "Upload": "GraphQLFile"
        default: escape(name)
        }
    }
}

private let swiftKeywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
    "init", "inout", "internal", "let", "operator", "private", "protocol", "public", "rethrows",
    "static", "struct", "subscript", "typealias", "var", "break", "case", "continue", "default",
    "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch",
    "where", "while", "as", "Any", "catch", "false", "is", "nil", "super", "self", "Self", "throw",
    "throws", "true", "try", "await", "async", "actor", "isolated", "nonisolated"
]

private func escape(_ name: String) -> String {
    swiftKeywords.contains(name) ? "`\(name)`" : name
}

private func camelCase(_ value: String) -> String {
    let parts = value.split(separator: "_").map(String.init)
    guard let first = parts.first else { return escape(value) }
    let head = first.lowercased()
    let tail = parts.dropFirst().map { part -> String in
        guard let char = part.first else { return part }
        return char.uppercased() + part.dropFirst().lowercased()
    }
    var result = ([head] + tail).joined()
    if result.first?.isNumber == true {
        result = "_" + result
    }
    return result
}
